### ISSUE TITLE
Suggestion: Support finite fluid

### ISSUE THREAD

**Issue by Joxxs** [EPIICTHUNDERCAT/Slurp#1]
Since you are properly raytracing if you check if it is source block and set block to air 
It could support both finite and infinite water setups.

Had to do same thing with my personal compiled copy of tan replacing the fillbottlehandler for finite fluid

```
		if(targetMaterial == Material.WATER && ((Integer) targetState.getValue(BlockLiquid.LEVEL)).intValue() == 0){
				world.setBlockToAir(targetPOS);
```

**Comment by EPIICTHUNDERCAT** [comment]
This was added in 0.2 as a config option :D enjoy!
